// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB3ht2TeyTTIt4Phekv3jQyOMrir8jeX0',
    appId: '1:605731784604:web:d6b2b8dddd5683feb76a59',
    messagingSenderId: '605731784604',
    projectId: 'testing-cli-7c2e9',
    authDomain: 'testing-cli-7c2e9.firebaseapp.com',
    storageBucket: 'testing-cli-7c2e9.appspot.com',
    measurementId: 'G-QCFN0102YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevqDg79U7nNOqxes53ly3PIdxx4AnQSg',
    appId: '1:605731784604:android:6e79e2de738ec513b76a59',
    messagingSenderId: '605731784604',
    projectId: 'testing-cli-7c2e9',
    storageBucket: 'testing-cli-7c2e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ356kwxhIsN-QWsSb7STeABtyBGIgOtg',
    appId: '1:605731784604:ios:b2c97b9deb4fb3edb76a59',
    messagingSenderId: '605731784604',
    projectId: 'testing-cli-7c2e9',
    storageBucket: 'testing-cli-7c2e9.appspot.com',
    iosBundleId: 'com.techease.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ356kwxhIsN-QWsSb7STeABtyBGIgOtg',
    appId: '1:605731784604:ios:b2c97b9deb4fb3edb76a59',
    messagingSenderId: '605731784604',
    projectId: 'testing-cli-7c2e9',
    storageBucket: 'testing-cli-7c2e9.appspot.com',
    iosBundleId: 'com.techease.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB3ht2TeyTTIt4Phekv3jQyOMrir8jeX0',
    appId: '1:605731784604:web:425095c5ebd8b593b76a59',
    messagingSenderId: '605731784604',
    projectId: 'testing-cli-7c2e9',
    authDomain: 'testing-cli-7c2e9.firebaseapp.com',
    storageBucket: 'testing-cli-7c2e9.appspot.com',
    measurementId: 'G-2D9GGR0PVQ',
  );
}
